version: '3.4'

services:
  app:
    image: audiodriventalkingfacecontenedor
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all